[bindings.csharp]
cdylib_name = "qsharp_bridge"
access_modifier = "public"
global_methods_class_name = "QsharpBridge"

[bindings.kotlin]
package_name = "qsharp.bridge"
cdylib_name = "qsharp_bridge"

[bindings.python]
cdylib_name = "qsharp_bridge"